### PR TITLE
use hasMethod instead of methodExists

### PR DESCRIPTION
**Pull request by wernerkrauss**
## Issue
- https://github.com/silverstripe/silverstripe-lumberjack/issues/125

### CODE REVIEW

**Comment by wernerkrauss** [comment]
I worked against the 2 branch, as the current project is on SS4.

**Comment by GuySartorelli** [comment]
Thanks for this.
In future, please make sure to include (at a bare minimum) the issue that the PR relates to in the PR description. I've added it for you this time.

**Comment by GuySartorelli** [comment]
You say you worked against the `2` branch - but this PR targets the `3` branch. I think this is an enhancement, and therefore it _should_ be targetted against the `3` branch, but just in case I'll give you a chance to respond before I merge this.

If this is fixing a _bug_ - please describe exactly what the bug is, and retarget this PR to the `2.3` branch.

**Comment by wernerkrauss** [comment]
IMHO it's kind of a bug, cause normally one can decorate classes with extensions and the methods in the extensions work magically like normal methods. That's the whole reason why `hasMethod()`exists.

This fix enables you to modify a 3rd party lumberjack config the "Silverstripe way" in an `Extension` subclass without touching 3rd party code.

**Comment by GuySartorelli** [comment]
Hmmmm I'm a fence sitter on the definition of bug vs enhancement in this case but it's a very low risk change that doesn't affect the API at all so I'm okay with it being released as a patch.

**Comment by wernerkrauss** [comment]
Thanks for helping me getting the PR right and for merging it.

**Comment by GuySartorelli** [comment]
No worries, thanks for your efforts submitting this 👍

**Pull request merged**
