### PR TITLE
Show SiteTree_Live table records

### PR DESCRIPTION
**Pull request by silbinarywolf**
Show SiteTree_Live data that no longer exists on the SiteTree draft table.

**Relies on this PR's acceptance:** 
https://github.com/silverstripe-australia/silverstripe-gridfieldextensions/pull/150
or:
https://github.com/silverstripe/silverstripe-framework/pull/5726

### CODE REVIEW

**Comment by SilbinaryWolf** [comment]
Updated PR to use a seperate GridField showing the published pages. It's title also prompts the user with "$this->getLumberjackTitle() . ' (Items to be deleted)'" if they've somehow accidentally deleted a draft page with unpublishing.

This is less of an issue with 3.2 since it uses a single 'Archive' button. But I need this to function on a 3.1 site.

**Comment by tractorcow** [comment]
So what happens if you edit pages in the second "live" gridfield... does it modify records directly on live? 

Archive is the solution we had to this problem, so it feels a bit weird to shiv this in to support 3.1 at the expense of 3.2.

I feel this code could live in a custom extension in user-code land. Do you agree?

Also, https://github.com/silverstripe/silverstripe-framework/pull/5799 has been raised to address your other issue with sorting. I hope that helps. :)

**Comment by SilbinaryWolf** [comment]
If you edit pages in the second live gridfield, it opens the page in a readonly state and has an unpublish/restore button. The second gridfield only shows *_Live items that have been deleted from draft.

I disagree with putting it in an extension because data could still enter a 'deleted from draft but still published' state in 3.2 if a developer has done something odd with the data (ie. deletes from stage, but doesnt delete from *_Live due to hitting a bug with a module just after the first delete.) 

With this, it makes it easier to debug/notice when data enters this sort of glitchy state.

Im not a fan of adding unnecessary code complexity, but I'd much rather something tell me when something has gone awry in the CMS rather than things -seemingly- working OK.

**Comment by micmania1** [comment]
I think 'Deleted from draft' should be represented as a state (along with published/draft) in the main GridField. Even in 3.2 you can still end up in this state if your code allows, so I think any solution needs to take that into account.

Having multiple GridFields will be extremely confusing for content editors so I wouldn't be happy merging as is (sorry).

**Comment by SilbinaryWolf** [comment]
I did that initially, but it fell apart (Maintaining code that extends and adds GridFieldOrderableRows so you can re-order the items, and GridFieldOrderableRows just wont work with ArrayList)

Also look at the latest commit. It only shows 2 gridfields IF there's a 'Deleted from draft, but published' item in the list. Otherwise it looks how it always did.

**Comment by dhensby** [comment]
Changed this to target `1.3` as it looks like a patch and `master` is targeting SS 4

**Comment by robbieaverill** [comment]
Hey @silbinarywolf, do you fancy reviving this pull request?

**Comment by silbinarywolf** [comment]
Id honestly love to, amongst other things. I just don't have the resources right now. I'll add it to my backlog though.

What's your expectation for the updated PR? Targetting SS4 + add some tests?

**Comment by robbieaverill** [comment]
Yeah that'd be great. I'll leave the PR open for a while and see if you get time :)

**Comment by silbinarywolf** [comment]
@robbieaverill I'm unfortunately not going to be able to cover this off.
Apologies.

**Pull request closed without merging**
