### PR TITLE
FIX Ensure correct link is used when gridfield is readonly

### PR DESCRIPTION
**Pull request by AljosaB**
Requires https://github.com/silverstripe/silverstripe-framework/pull/11228

## Issue
-  https://github.com/silverstripe/silverstripe-lumberjack/issues/89

### CODE REVIEW

**Comment by NightJar** [comment]
I agree with @robbieaverill - only a single class needs to be introduced (the new `GridFieldSiteTreeViewButton` you've created @AljosaB), and edits to the components for the `GridField` would be more appropriate in `GridFieldConfig_Lumberjack` :)

**Comment by AljosaB** [comment]
The thing is, there is no View button in GridField config, so I can not replace it. There is Edit button that gets replaced later when canEdit check is made

LeftAndMain::getEditForm
```
if (!$record->canEdit()) {
	$readonlyFields = $form->Fields()->makeReadonly();
	$form->setFields($readonlyFields);
}
```
and in the end View button is added in GridField::performReadonlyTransformation
```
// As the edit button may have been removed, add a view button if it doesn't have one
if (!$copyConfig->getComponentByType(GridFieldViewButton::class)) {
	$copyConfig->addComponent(new GridFieldViewButton);
```

I didn't find any hook after that to replace View button with my extended View button, that's why I had to introduce an extended GridField and overload performReadonlyTransformation function. I hope you find a better solution.

**Comment by robbieaverill** [comment]
I'll take a look at this later this week :)

**Comment by GuySartorelli** [comment]
I've updated this PR to use the newish API for updating the set of readonly components.
It requires a companion PR in framework so the correct view button class is used.

**Review by emteknetnz — APPROVED** [review]
Tested locally, works well

**Pull request merged**
