### PR TITLE
FIX only exclude SiteTree subclasses if there are any set.

### PR DESCRIPTION
**Pull request by fspringveldt**
LumberJack::liveChildren() and LumberJack::stageChildren() should check if count(LumberJack::getExcludedSiteTreeClassNames()) > 0 to avoid an `InvalidArgumentException` exception being thrown by DataList::exclude().

### CODE REVIEW

**Comment by robbieaverill** [comment]
I think we should make this PR for the SS3 compatible version and merge up.

Have requested a review from @micmania1 for the logic

**Comment by robbieaverill** [comment]
We need to update the travis config - logged as #61

**Comment by fspringveldt** [comment]
Okay, rebased off 1.3 branch instead.

**Comment by micmania1** [comment]
I think the check can just be added to the `shouldFilter()` function.

The reason being; it's a bit misleading when `shouldFilter()` returns true because that implies that we should filter, but then we don't because `count()` returns 0.

**Comment by fspringveldt** [comment]
Thanks @micmania1 

> I think the check can just be added to the shouldFilter() function.

I considered this (after @robbieaverill suggested it too), but decided against. 

The responsibility of shouldFilter() is "Checks if we're on a controller where we should filter". 

This additional check (::excludeSiteTreeClassNames()) mutates a DataList based on whether we _shouldFilter()_ __and__ if there any configured hidden subclasses (result of ::getExcludedSiteTreeClassNames()).  

Thus, implementing this on LumberJack::shouldFilter() would mean updating everywhere it's used (e.g. BlogFilter::stageChildren()), which doesn't necessarily care about hidden subclasses.

Thoughts?

**Comment by micmania1** [comment]
I can see how it would affect blog. In that case could you just make the new method `excludeSiteTreeClassNames` protected since its only use is internal? If we need to make it public later we can do that easily without introducing breaking changes.

Could you also add further notes to the `shouldFilter` docblocks so that its absolutely clear that it only checks the current controller and maybe link back to this discussion?

**Pull request merged**
