### PR TITLE
Added Helpful Robot badge

### PR DESCRIPTION
**Pull request by assertchris**

### CODE REVIEW

**Comment by spekulatius** [comment]
Hey @assertchris 

thanks :) What does the value in the batch stand for?

Cheers,
Peter

**Comment by assertchris** [comment]
It's the stats from https://helpfulrobot.io/silverstripe/lumberjack and http://addons.silverstripe.org/add-ons/silverstripe/lumberjack.

**Comment by spekulatius** [comment]
That was my first thought too. But when I checked it the score for lumberjack was 74, not 69. Maybe thats from a background/different process which updates the value?

**Comment by assertchris** [comment]
The score on addons.silverstripe.org is adjusted to remove the code of conduct points. The score on helpfulrobot.io is not.

**Pull request merged**
