### PR TITLE
FIX Deleted child pages now show in gridfield

### PR DESCRIPTION
**Pull request by dhensby**
Fixes #18

### CODE REVIEW

**Comment by tractorcow** [comment]
Won't this fix show pages that are deleted from both the stage AND live?

**Comment by dhensby** [comment]
Erm, the intent is to show anything :P as there is not filtering, this gets around the problem of not being able to see deleted pages.

It uses the same logic as is used to generate the SiteTree (when showing deleted pages).

**Comment by micmania1** [comment]
I don't think deleted pages should show in the gridfield by default. Just anything that is in Stage or Live.

Showing deleted pages would be a good feature to add but there would have to be some thought given as to how its implemented. Something like a 'View Archive Pages' Gridfield component which can be toggled by the user would be good. Maybe it should be added to the existing SiteTree component?

**Comment by dhensby** [comment]
Closing this for now as others are submitting better resolitions

**Pull request closed without merging**
