### PR TITLE
Update build icons

### PR DESCRIPTION
**Pull request by tractorcow**
When we merge up to master I'll update the travis branch to master then. For 1.1 it should be the stable branch.

### CODE REVIEW

**Comment by assertchris** [comment]
What is the point of listing the number of downloads? Without the context of time, repo activity, and quality ratings; this is a useless badge.

**Comment by tractorcow** [comment]
The intent is just to fix the current incorrect links; Do you think instead we should just remove them?

**Comment by assertchris** [comment]
I think we could add more meaningful ones; like code coverage, static analysis (Scrutinizer), latest stable version number, and licence. The build status is the only badge that makes sense in this...

**Comment by tractorcow** [comment]
It looks like we should remove hhvm tests too

https://github.com/travis-ci/travis-ci/issues/3788

**Comment by micmania1** [comment]
The number of downloads is important for people choosing whether or not to use the module. The more uses, the more confident a user will be to pick it up. 

Quite a lengthy discussion here: https://groups.google.com/forum/#!searchin/silverstripe-dev/module$20quality/silverstripe-dev/wZM23FbOb2w/UNH2CltZpxcJ

**Comment by tractorcow** [comment]
I kind of agree with @micmania1 but I didn't really feel that strongly about it. Perhaps we should add them abck in, @assertchris ?

**Comment by assertchris** [comment]
My opinion is that context-free download counts are meaningless. I don't care enough about it to debate the point here, though. :)

Add it back if you want it back. I won't try to remove it or anything...

**Pull request merged**
